In [4]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report

In [6]:
df = pd.read_csv('/diabetes.csv')

In [7]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [10]:
scaler = MinMaxScaler()
df['Glucose'] = scaler.fit_transform(df[['Glucose']])
df['BloodPressure'] = scaler.fit_transform(df[['BloodPressure']])
df['SkinThickness'] = scaler.fit_transform(df[['SkinThickness']])
df['BMI'] = scaler.fit_transform(df[['BMI']])
df['Age'] = scaler.fit_transform(df[['Age']])
df['Insulin'] = scaler.fit_transform(df[['Insulin']])

In [11]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,0.743719,0.590164,0.353535,0.000000,0.500745,0.627,0.483333,1
1,1,0.427136,0.540984,0.292929,0.000000,0.396423,0.351,0.166667,0
2,8,0.919598,0.524590,0.000000,0.000000,0.347243,0.672,0.183333,1
3,1,0.447236,0.540984,0.232323,0.111111,0.418778,0.167,0.000000,0
4,0,0.688442,0.327869,0.353535,0.198582,0.642325,2.288,0.200000,1
...,...,...,...,...,...,...,...,...,...
763,10,0.507538,0.622951,0.484848,0.212766,0.490313,0.171,0.700000,0
764,2,0.613065,0.573770,0.272727,0.000000,0.548435,0.340,0.100000,0
765,5,0.608040,0.590164,0.232323,0.132388,0.390462,0.245,0.150000,0
766,1,0.633166,0.491803,0.000000,0.000000,0.448584,0.349,0.433333,1
767,1,0.467337,0.573770,0.313131,0.000000,0.453055,0.315,0.033333,0

In [12]:
x = df.drop('Outcome',axis=1)
y = df['Outcome']

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8, shuffle = True, random_state=42)

In [23]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [24]:
y_pred = model.predict(x_test)

In [25]:
print(confusion_matrix(y_test,y_pred))

[[86 13]
 [21 34]]

In [26]:
print(accuracy_score(y_test, y_pred))

0.7792207792207793

In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83        99
           1       0.72      0.62      0.67        55

    accuracy                           0.78       154
   macro avg       0.76      0.74      0.75       154
weighted avg       0.78      0.78      0.77       154